import {
  FiActivity,
  FiArchive,
  FiAward,
  FiBarChart2,
  FiBell,
  FiBook,
  FiBookOpen,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiCheckCircle,
  FiCheckSquare,
  FiClipboard,
  FiClock,
  FiCloud,
  FiCode,
  FiCreditCard,
  FiDatabase,
  FiDollarSign,
  FiFileText,
  FiFolder,
  FiGift,
  FiGitBranch,
  FiGrid,
  FiHeadphones,
  FiImage,
  FiMail,
  FiMapPin,
  FiMessageSquare,
  FiMonitor,
  FiPackage,
  FiPhone,
  FiPieChart,
  FiRepeat,
  FiServer,
  FiSettings,
  FiShield,
  FiShoppingBag,
  FiShoppingCart,
  FiTarget,
  FiTrendingUp,
  FiTruck,
  FiUser,
  FiUserPlus,
  FiUsers,
  FiZap,
} from 'react-icons/fi';
import {
  LuBuilding2,
  LuClipboardCheck,
  LuFactory,
  LuPiggyBank,
  LuPlug,
  LuReceipt,
  LuScrollText,
  LuSparkles,
} from 'react-icons/lu';
import type {IconType} from 'react-icons';

/* Stored as `iconCode`. Codes are semantic (the icon's purpose)
 * so suppliers pick by meaning, not by glyph. All drawn from the Feather
 * family for visual consistency. Adding an entry here surfaces it in the
 * product form picker and renders it via <ProductIcon> — nothing else to wire. */
export const MARKETPLACE_ICONS: {
  code: string;
  label: string;
  Icon: IconType;
}[] = [
  {code: 'automation', label: 'Automation', Icon: FiZap},
  {code: 'analytics', label: 'Analytics', Icon: FiBarChart2},
  {code: 'dashboard', label: 'Dashboard', Icon: FiGrid},
  {code: 'reporting', label: 'Reporting', Icon: FiPieChart},
  {code: 'finance', label: 'Finance', Icon: FiDollarSign},
  {code: 'accounting', label: 'Accounting', Icon: FiBook},
  {code: 'invoicing', label: 'Invoicing', Icon: FiFileText},
  {code: 'payments', label: 'Payments', Icon: FiCreditCard},
  {code: 'sales', label: 'Sales', Icon: FiTrendingUp},
  {code: 'crm', label: 'CRM', Icon: FiUsers},
  {code: 'contacts', label: 'Contacts', Icon: FiUser},
  {code: 'marketing', label: 'Marketing', Icon: FiTarget},
  {code: 'inventory', label: 'Inventory', Icon: FiPackage},
  {code: 'warehouse', label: 'Warehouse', Icon: FiBox},
  {code: 'logistics', label: 'Logistics', Icon: FiTruck},
  {code: 'ecommerce', label: 'E-commerce', Icon: FiShoppingCart},
  {code: 'pos', label: 'Point of sale', Icon: FiShoppingBag},
  {code: 'manufacturing', label: 'Manufacturing', Icon: LuFactory},
  {code: 'project', label: 'Project', Icon: FiClipboard},
  {code: 'tasks', label: 'Tasks', Icon: FiCheckSquare},
  {code: 'calendar', label: 'Calendar', Icon: FiCalendar},
  {code: 'scheduling', label: 'Scheduling', Icon: FiClock},
  {code: 'hr', label: 'Human resources', Icon: FiBriefcase},
  {code: 'recruitment', label: 'Recruitment', Icon: FiUserPlus},
  {code: 'documents', label: 'Documents', Icon: FiFolder},
  {code: 'email', label: 'Email', Icon: FiMail},
  {code: 'messaging', label: 'Messaging', Icon: FiMessageSquare},
  {code: 'integration', label: 'Integration', Icon: LuPlug},
  {code: 'api', label: 'API / Developer', Icon: FiCode},
  {code: 'ai', label: 'AI', Icon: LuSparkles},
  {code: 'security', label: 'Security', Icon: FiShield},
  {code: 'helpdesk', label: 'Helpdesk', Icon: FiHeadphones},
  {code: 'database', label: 'Database', Icon: FiDatabase},
  {code: 'cloud', label: 'Cloud', Icon: FiCloud},
  {code: 'settings', label: 'Settings', Icon: FiSettings},
  {code: 'quality', label: 'Quality', Icon: FiAward},
  {code: 'locations', label: 'Locations', Icon: FiMapPin},
  {code: 'notifications', label: 'Notifications', Icon: FiBell},
  {code: 'workflow', label: 'Workflow', Icon: FiGitBranch},
  {code: 'approvals', label: 'Approvals', Icon: FiCheckCircle},
  {code: 'forecasting', label: 'Forecasting', Icon: FiActivity},
  {code: 'budget', label: 'Budget', Icon: LuPiggyBank},
  {code: 'subscriptions', label: 'Subscriptions', Icon: FiRepeat},
  {code: 'contracts', label: 'Contracts', Icon: LuScrollText},
  {code: 'expenses', label: 'Expenses', Icon: LuReceipt},
  {code: 'purchasing', label: 'Purchasing', Icon: LuClipboardCheck},
  {code: 'assets', label: 'Assets', Icon: LuBuilding2},
  {code: 'knowledge', label: 'Knowledge base', Icon: FiBookOpen},
  {code: 'monitoring', label: 'Monitoring', Icon: FiMonitor},
  {code: 'infrastructure', label: 'Infrastructure', Icon: FiServer},
  {code: 'backup', label: 'Backup', Icon: FiArchive},
  {code: 'telephony', label: 'Telephony', Icon: FiPhone},
  {code: 'media', label: 'Media', Icon: FiImage},
  {code: 'loyalty', label: 'Loyalty', Icon: FiGift},
];

export const MARKETPLACE_ICON_MAP: Record<string, IconType> =
  Object.fromEntries(MARKETPLACE_ICONS.map(({code, Icon}) => [code, Icon]));

export const DEFAULT_ICON_CODE = MARKETPLACE_ICONS[0].code;
