/*
 * The environment variables releases before the configuration document read,
 * each with the variable that carries the same setting now, or null for one
 * nothing carries any more.
 *
 * Two readers: the loader, to tell an operator who upgraded without migrating
 * which of their variables it is ignoring and what to run, and the migration
 * script, which writes the new variables from these. `<ID>` stands for the
 * tenant id, which the old variables never named because there was one tenant.
 */
export const LEGACY_ENV: ReadonlyMap<string, string | null> = new Map<
  string,
  string | null
>([
  ['BETTER_AUTH_URL', 'PORTAL_ORIGIN'],
  ['BETTER_AUTH_SECRET', 'PORTAL_TENANT_<ID>_SESSION_SECRET'],
  ['PUSH_MAX_CONNECTIONS', 'PORTAL_PUSH_MAX_CONNECTIONS'],
  ['IMAGE_CACHE_MAX_BYTES', 'PORTAL_IMAGE_CACHE_MAX_BYTES'],
  ['DATABASE_URL', 'PORTAL_TENANT_<ID>_DB_URL'],
  ['AOS_URL', 'PORTAL_TENANT_<ID>_AOS_URL'],
  ['AOS_TENANT_ID', 'PORTAL_TENANT_<ID>_AOS_TENANT_ID'],
  ['DATA_STORAGE', 'PORTAL_TENANT_<ID>_AOS_STORAGE'],
  ['AOS_API_KEY', 'PORTAL_TENANT_<ID>_AOS_AUTH_API_KEY'],
  ['BASIC_AUTH_USERNAME', 'PORTAL_TENANT_<ID>_AOS_AUTH_USERNAME'],
  ['BASIC_AUTH_PASSWORD', 'PORTAL_TENANT_<ID>_AOS_AUTH_PASSWORD'],
  ['NOTIFICATION_WEBHOOK_SECRET', 'PORTAL_TENANT_<ID>_AOS_WEBHOOK_SECRET'],
  ['PAYPAL_CLIENT_ID', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYPAL_CLIENT_ID'],
  ['PAYPAL_CLIENT_SECRET', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYPAL_CLIENT_SECRET'],
  ['PAYPAL_LIVE', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYPAL_LIVE'],
  ['STRIPE_CLIENT_ID', null],
  ['STRIPE_CLIENT_SECRET', 'PORTAL_TENANT_<ID>_PAYMENTS_STRIPE_CLIENT_SECRET'],
  [
    'STRIPE_WEBHOOK_SECRET',
    'PORTAL_TENANT_<ID>_PAYMENTS_STRIPE_WEBHOOK_SECRET',
  ],
  ['PBX_SITE', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYBOX_SITE'],
  ['PBX_RANG', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYBOX_RANG'],
  ['PBX_IDENTIFIANT', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYBOX_IDENTIFIANT'],
  ['PBX_SECRET', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYBOX_SECRET'],
  ['PBX_PAYBOX', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYBOX_PAYBOX'],
  ['PBX_BACKUP1', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYBOX_BACKUP1'],
  ['PBX_BACKUP2', 'PORTAL_TENANT_<ID>_PAYMENTS_PAYBOX_BACKUP2'],
  ['UP2PAY_SITE', 'PORTAL_TENANT_<ID>_PAYMENTS_UP2PAY_SITE'],
  ['UP2PAY_RANG', 'PORTAL_TENANT_<ID>_PAYMENTS_UP2PAY_RANG'],
  ['UP2PAY_IDENTIFIANT', 'PORTAL_TENANT_<ID>_PAYMENTS_UP2PAY_IDENTIFIANT'],
  ['UP2PAY_SECRET', 'PORTAL_TENANT_<ID>_PAYMENTS_UP2PAY_SECRET'],
  ['UP2PAY_PAYBOX', 'PORTAL_TENANT_<ID>_PAYMENTS_UP2PAY_PAYBOX'],
  [
    'UP2PAY_LEGACY_FORWARD_URL',
    'PORTAL_TENANT_<ID>_PAYMENTS_UP2PAY_LEGACY_FORWARD_URL',
  ],
  ['HUBPISP_TOKEN_URL', 'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_TOKEN_URL'],
  ['HUBPISP_API_URL', 'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_API_URL'],
  ['HUBPISP_CLIENT_ID', 'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_CLIENT_ID'],
  [
    'HUBPISP_CLIENT_SECRET',
    'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_CLIENT_SECRET',
  ],
  [
    'HUBPISP_CERT_FINGERPRINT',
    'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_CERT_FINGERPRINT',
  ],
  [
    'HUBPISP_BENEFICIARY_NAME',
    'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_BENEFICIARY_NAME',
  ],
  ['HUBPISP_IBAN', 'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_IBAN'],
  ['HUBPISP_BIC', 'PORTAL_TENANT_<ID>_PAYMENTS_HUBPISP_BIC'],
  ['MAIL_HOST', 'PORTAL_TENANT_<ID>_MAIL_HOST'],
  ['MAIL_PORT', 'PORTAL_TENANT_<ID>_MAIL_PORT'],
  ['MAIL_SECURE', 'PORTAL_TENANT_<ID>_MAIL_SECURE'],
  ['MAIL_USER', 'PORTAL_TENANT_<ID>_MAIL_USER'],
  ['MAIL_PASSWORD', 'PORTAL_TENANT_<ID>_MAIL_PASSWORD'],
  ['MAIL_EMAIL', 'PORTAL_TENANT_<ID>_MAIL_EMAIL'],
  ['MAIL_MAX_CONNECTIONS', 'PORTAL_TENANT_<ID>_MAIL_MAX_CONNECTIONS'],
  ['MATTERMOST_TOKEN', 'PORTAL_TENANT_<ID>_MATTERMOST_TOKEN'],
  ['CREATE_MATTERMOST_USERS', 'PORTAL_TENANT_<ID>_MATTERMOST_CREATE_USERS'],
  ['GOOGLE_CLIENT_ID', 'PORTAL_TENANT_<ID>_OAUTH_GOOGLE_CLIENT_ID'],
  ['GOOGLE_CLIENT_SECRET', 'PORTAL_TENANT_<ID>_OAUTH_GOOGLE_CLIENT_SECRET'],
  ['SHOW_GOOGLE_OAUTH', null],
  ['KEYCLOAK_ID', 'PORTAL_TENANT_<ID>_OAUTH_KEYCLOAK_CLIENT_ID'],
  ['KEYCLOAK_SECRET', 'PORTAL_TENANT_<ID>_OAUTH_KEYCLOAK_CLIENT_SECRET'],
  ['KEYCLOAK_ISSUER', 'PORTAL_TENANT_<ID>_OAUTH_KEYCLOAK_ISSUER'],
  ['SHOW_KEYCLOAK_OAUTH', null],
  ['VAPID_PRIVATE_KEY', 'PORTAL_TENANT_<ID>_WEB_PUSH_PRIVATE_KEY'],
  ['VAPID_SUBJECT', 'PORTAL_TENANT_<ID>_WEB_PUSH_SUBJECT'],
  ['INCLUDE_LANGUAGE', 'PORTAL_TENANT_<ID>_INCLUDE_LANGUAGE'],
  [
    'UPLOAD_RECORD_RETENTION_HOURS',
    'PORTAL_TENANT_<ID>_UPLOAD_RECORD_RETENTION_HOURS',
  ],
  ['MULTI_TENANCY', null],
  ['GOOVEE_PUBLIC_HOST', 'PORTAL_TENANT_<ID>_PUBLIC_HOST'],
  [
    'GOOVEE_PUBLIC_PAYPAL_CLIENT_ID',
    'PORTAL_TENANT_<ID>_PUBLIC_PAYPAL_CLIENT_ID',
  ],
  [
    'GOOVEE_PUBLIC_VAPID_PUBLIC_KEY',
    'PORTAL_TENANT_<ID>_PUBLIC_WEB_PUSH_PUBLIC_KEY',
  ],
  [
    'GOOVEE_PUBLIC_MATTERMOST_HOST',
    'PORTAL_TENANT_<ID>_PUBLIC_MATTERMOST_HOST',
  ],
  [
    'GOOVEE_PUBLIC_KEYCLOAK_OAUTH_BUTTON_LABEL',
    'PORTAL_TENANT_<ID>_PUBLIC_KEYCLOAK_BUTTON_LABEL',
  ],
  [
    'GOOVEE_PUBLIC_KEYCLOAK_OAUTH_BUTTON_IMAGE',
    'PORTAL_TENANT_<ID>_PUBLIC_KEYCLOAK_BUTTON_IMAGE',
  ],
  ['GOOVEE_PUBLIC_LINKEDIN_URL', 'PORTAL_TENANT_<ID>_PUBLIC_LINKS_LINKEDIN'],
  ['GOOVEE_PUBLIC_TWITTER_URL', 'PORTAL_TENANT_<ID>_PUBLIC_LINKS_TWITTER'],
  ['GOOVEE_PUBLIC_INSTAGRAM_URL', 'PORTAL_TENANT_<ID>_PUBLIC_LINKS_INSTAGRAM'],
  ['GOOVEE_PUBLIC_WHATSAPP_URL', 'PORTAL_TENANT_<ID>_PUBLIC_LINKS_WHATSAPP'],
]);

/** The legacy variables an environment still carries. */
export function legacyNamesIn(
  env: Readonly<Record<string, string | undefined>>,
): string[] {
  return [...LEGACY_ENV.keys()].filter(name => env[name] !== undefined);
}
