/*
 * The configuration document's shape, in one place.
 *
 * Three things are derived from what is written here: the parse every document
 * is admitted by, the TypeScript types the application reads configuration
 * through, and tenants.config.schema.json — generated by `pnpm config:schema`,
 * and what an operator's editor validates the document against. Adding a
 * setting means adding it here and regenerating, rather than writing it into a
 * type, a check and a schema file that are free to disagree.
 *
 * A `describe()` string is operator-facing: it is what the generated schema
 * carries and what an editor shows while the document is being written.
 */

import path from 'path';

import {z} from 'zod';

import {
  getMaxConnections,
  mailAccountKey,
} from '@/lib/core/notification/mail-account';
import {
  isReservedSegment,
  reservedSegments,
} from '@/lib/core/path/reserved-segments';

/* $schema is an editor hint and $global holds the deployment-wide settings.
 * Every other key in the document names a tenant. */
const RESERVED_DOCUMENT_KEYS = ['$schema', '$global'];

/*
 * A tenant id is the URL path segment the tenant is served under. `extractTenant`
 * in proxy.ts matches that segment with its own copy of this pattern, so widen
 * both together: an id only one of them accepts names an entry no request
 * reaches.
 *
 * The first character must be a letter. The proxy reads the first segment of an
 * address as a tenant name, so `_next`, `_not-found`, a digit or a dot must not
 * look like one. After the first character only `~` has to stay out: an Up2Pay
 * notification carries `<reference>~<contextId>~<tenantId>` and is attributed
 * by splitting on it.
 */
const TENANT_ID_PATTERN = /^[a-zA-Z][a-zA-Z0-9-]*$/;

/* Reserving the whole width a payment context id can reach: a Hub PISP payment
 * carries `${contextId}-${tenantId}` in a field of 35 characters, and a context
 * id is a bigint sequence, so its 19 digits and the separator leave 15. */
const TENANT_ID_MAX_LENGTH = 15;

/*
 * A positive whole number.
 *
 * Rejected at load rather than corrected at the point of use: a setting
 * silently replaced by a default is how a deployment ends up believing it set
 * three and running at ten.
 */
const positiveInteger = () => z.int().min(1);

/*
 * The hostnames the auth library's own host check accepts: DNS labels of at
 * most 63 characters, an IPv4 literal (which those labels already cover), or a
 * bracketed IPv6 literal. An underscore is the character that occurs in
 * practice and is not among them.
 */
const HOSTNAME_PATTERN =
  /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*|\[[0-9a-fA-F:]+\])$/;

/*
 * Whether a value is an origin this deployment can be reached at, spelled the
 * way an origin is spelled.
 *
 * Exactness matters because nothing parses the value again. Absolute addresses
 * are built by concatenating onto it, so anything trailing the host survives into
 * them: a lone trailing slash emails `<host>//auth/reset-password/…`, which
 * matches no tenant and no reserved segment, so the proxy answers not-found.
 * Stored workspace addresses are matched by string prefix against it, so a
 * spelling that differs from the canonical one — a default port written out, an
 * uppercase host — matches none of them and the tenant resolves no workspace.
 *
 * Refused rather than corrected to the canonical spelling, because this value is
 * typed into AOS as well, as the prefix of every workspace address held there.
 * Repairing only the copy in this document would leave the two disagreeing.
 *
 * The host is restricted to what the auth library accepts, because one it
 * refuses is resolved from the request URL by the request handler and from the
 * configured origin by a server-side session read. An OAuth redirect address
 * built under the first is not the one registered under the second, and the
 * identity provider refuses it.
 */
function isDeploymentOrigin(value: string): boolean {
  return parseOrigin(value) !== null;
}

/* The parsed form of an origin, or null for a value that is not one. Callers
 * that need to read a part of it go through this rather than `new URL`, which
 * throws — and a throw raised while the document is being checked escapes the
 * parse, so a mistyped origin would be reported as an unhandled TypeError
 * naming neither the field nor the tenant. */
function parseOrigin(value: unknown): URL | null {
  if (typeof value !== 'string') return null;

  let url: URL;

  try {
    url = new URL(value);
  } catch {
    return null;
  }

  /* An origin holds a scheme and a host and can hold nothing else, so equality
   * with the parsed origin settles the trailing characters and the canonical
   * spelling at once. It settles nothing about the scheme: `ftp://`, `ws://` and
   * `wss://` each parse to an origin equal to what was written, so the protocol
   * test beside it is what admits only the two a deployment is served over. */
  const isOrigin =
    (url.protocol === 'http:' || url.protocol === 'https:') &&
    value === url.origin &&
    HOSTNAME_PATTERN.test(url.hostname);

  return isOrigin ? url : null;
}

const ORIGIN_ERROR =
  'must be written as an origin — a scheme and a host, with no path, query, ' +
  'fragment or trailing slash, e.g. https://portal.example.com';

/* What the generated schema carries. Looser than the load on purpose: spelling
 * the host rule as a regex leaves an editor showing something unreadable, so an
 * editor admits a host the load then refuses. */
const ORIGIN_PATTERN = '^https?://[^/?#]+$';

export const globalConfigSchema = z
  .strictObject({
    betterAuthSecret: z
      .string()
      .min(1)
      .describe(
        'Better Auth signing/encryption secret (the BETTER_AUTH_SECRET equivalent).',
      ),
    betterAuthUrl: z
      .string()
      .min(1)
      .refine(isDeploymentOrigin, {error: ORIGIN_ERROR})
      .meta({
        description:
          "Origin serving the addresses that name no tenant — \"/\" and the sign-in screens — e.g. https://portal.example.com, scheme and host only with no trailing slash. Every tenant's own origin (publicEnv.GOOVEE_PUBLIC_HOST) is trusted for authentication alongside it, and a request arriving on a host none of them names is answered under this one. Its scheme decides whether the deployment's session cookies are written as __Secure-, so every origin in the document has to share it. Required: left out, Better Auth resolves an origin from the environment instead, where an unrelated BASE_URL becomes this deployment's auth origin and its only trusted origin.",
        pattern: ORIGIN_PATTERN,
      }),
    defaultTenant: z
      .string()
      .min(1)
      .describe(
        'Tenant serving the addresses that name none of their own: "/" and the sign-in screens, which sit outside the tenant path segment, and a script run with no --tenant. Must name an entry of this document. Left out, those addresses resolve no tenant: "/" answers not-found, and a visitor reaches the sign-in screen by naming a tenant in the URL.',
      )
      .optional(),
    pushMaxConnections: positiveInteger()
      .describe(
        'Push deliveries in flight at once, and sockets held per push service. One agent serves the whole process, so this bounds the deployment. Defaults to 10.',
      )
      .optional(),
    imageCacheMaxBytes: positiveInteger()
      .describe(
        "Bytes the resized-image cache may occupy. One cache directory serves every tenant, so the budget is the deployment's.",
      )
      .optional(),
  })
  .describe(
    'Deployment-wide settings, shared by every tenant because they are bound to the single origin / process.',
  );

const publicEnvSchema = z
  .strictObject({
    GOOVEE_PUBLIC_HOST: z
      .string()
      .min(1)
      .refine(isDeploymentOrigin, {error: ORIGIN_ERROR})
      .meta({
        description:
          'Required. Origin this tenant is served on, e.g. https://portal.example.com — scheme and host only, with no trailing slash. Workspace URLs are stored against it, every absolute link is built from it, and the deployment trusts it as an origin to authenticate on, so a tenant without one resolves no workspace. Tenants sharing an origin is the ordinary case; the scheme must be the one $global.betterAuthUrl carries.',
        pattern: ORIGIN_PATTERN,
      }),
    GOOVEE_PUBLIC_PAYPAL_CLIENT_ID: z.string().optional(),
    GOOVEE_PUBLIC_LINKEDIN_URL: z.string().optional(),
    GOOVEE_PUBLIC_TWITTER_URL: z.string().optional(),
    GOOVEE_PUBLIC_INSTAGRAM_URL: z.string().optional(),
    GOOVEE_PUBLIC_WHATSAPP_URL: z.string().optional(),
    GOOVEE_PUBLIC_MATTERMOST_HOST: z.string().optional(),
    GOOVEE_PUBLIC_VAPID_PUBLIC_KEY: z.string().optional(),
    GOOVEE_PUBLIC_KEYCLOAK_OAUTH_BUTTON_LABEL: z.string().optional(),
    GOOVEE_PUBLIC_KEYCLOAK_OAUTH_BUTTON_IMAGE: z.string().optional(),
  })
  .describe(
    'Browser-exposed variables for this tenant (declared in full; not inherited from the environment).',
  );

/* The browser-exposed variables the app supports, taken from the schema so that
 * what a tenant may declare and what the app delivers cannot drift apart. */
export type PublicEnvKey = keyof z.output<typeof publicEnvSchema>;

/* The cast holds because a shape's keys are the keys of the type inferred from
 * it. */
export const PUBLIC_ENV_KEYS = Object.keys(
  publicEnvSchema.shape,
) as PublicEnvKey[];

const aosAuthSchema = z
  .strictObject({
    apiKey: z.string().optional(),
    username: z.string().optional(),
    password: z.string().optional(),
  })
  .refine(auth => !!auth.apiKey || !!(auth.username && auth.password), {
    error: 'requires apiKey, or username and password',
  })
  /* The alternative is a refinement, which no JSON Schema keyword expresses, so
   * the generated schema would accept credentials the load then refuses. Stated
   * here as well, in the keyword an editor understands. */
  .meta({
    description:
      'AOS credentials: apiKey (AOS 9+, generated in AOS under Preferences → API Keys) or username/password basic auth. apiKey wins when both are set.',
    anyOf: [{required: ['apiKey']}, {required: ['username', 'password']}],
  });

const aosSchema = z
  .strictObject({
    url: z
      .string()
      .min(1)
      .describe(
        'Base URL of the AOS instance, e.g. https://erp.example.com/axelor-erp. Unique per tenant in topology A (dedicated AOS); shared across tenants in topology B (AOS multi-tenancy).',
      ),
    aosTenantId: z
      .string()
      .describe(
        'AOS-side tenant id — independent of the Goovee tenant id. Set it when this tenant lives on a shared AOS instance with AOS multi-tenancy (topology B): every AOS call then carries X-Tenant-ID with this value. Leave unset for a dedicated AOS instance (topology A).',
      )
      .optional(),
    storage: z
      .string()
      .min(1)
      .describe(
        "The AOS instance's data.upload.dir base path (created on first connect; back it with a mounted volume so uploads survive). When aosTenantId is set (topology B), goovee reads and writes files under <storage>/<aosTenantId> to match AOP's per-tenant subdirectory; a dedicated instance (topology A) uses this path as-is.",
      ),
    auth: aosAuthSchema,
    webhookSecret: z
      .string()
      .describe(
        'Secret AOS uses to sign notification webhooks for this tenant (the NOTIFICATION_WEBHOOK_SECRET equivalent).',
      )
      .optional(),
  })
  /* Bake the per-tenant storage root once, mirroring AOP's
   * FileSystemStore.getRootPath(): a tenant on a shared multi-tenant AOS keeps
   * its files under <data.upload.dir>/<aosTenantId>, while a dedicated instance
   * (or the AOP "default" tenant) uses <data.upload.dir> as-is. goovee reads and
   * writes the AOS filesystem directly, so every storage consumer can use
   * config.aos.storage verbatim without re-deriving the subdirectory. */
  .transform(aos => ({
    ...aos,
    storage:
      aos.aosTenantId && aos.aosTenantId !== 'default'
        ? path.join(aos.storage, aos.aosTenantId)
        : aos.storage,
  }));

const paymentsSchema = z
  .strictObject({
    paypal: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        live: z
          .boolean()
          .describe('true for live payments; defaults to sandbox.')
          .optional(),
      })
      .optional(),
    stripe: z
      .strictObject({
        clientSecret: z.string().min(1),
        webhookSecret: z
          .string()
          .describe(
            "Stripe webhook signing secret for this tenant's webhook endpoint.",
          )
          .optional(),
      })
      .optional(),
    paybox: z
      .strictObject({
        site: z.string().min(1),
        rang: z.string().min(1),
        identifiant: z.string().min(1),
        secret: z.string().min(1),
        paybox: z.string().min(1).describe('Paybox payment page base URL.'),
        backup1: z.string().optional(),
        backup2: z.string().optional(),
      })
      .optional(),
    up2pay: z
      .strictObject({
        site: z.string().min(1),
        rang: z.string().min(1),
        identifiant: z.string().min(1),
        secret: z.string().min(1),
        paybox: z.string().min(1).describe('Up2Pay payment page base URL.'),
        legacyForwardUrl: z
          .string()
          .describe(
            'Where to forward Up2Pay IPNs this tenant cannot attribute to a Goovee payment (legacy-ERP invoices, unknown context). Omit to not forward.',
          )
          .optional(),
      })
      .optional(),
    hubpisp: z
      .strictObject({
        tokenUrl: z.string().min(1),
        apiUrl: z.string().min(1),
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        certFingerprint: z.string().min(1),
        beneficiaryName: z
          .string()
          .min(1)
          .max(70)
          .describe(
            'Name of the account a payment is credited to, at most 70 characters — the ISO 20022 limit for a creditor name. The value is sent as it stands, with nothing truncating it on the way out.',
          ),
        iban: z.string().min(1),
        bic: z.string().optional(),
        certsDir: z
          .string()
          .min(1)
          .describe(
            "Required. Directory holding this tenant's mTLS client.crt and private-key.pem. Must be distinct per HUB PISP tenant — the certificate is the tenant's bank identity, so there is no shared default. Uniqueness is enforced at config load, not by this schema.",
          ),
      })
      .describe(
        "Register this tenant's BPCE webhook under the tenant-scoped path /api/tenant/<tenantId>/webhooks/hubpisp/... so the webhook uses this tenant's credentials.",
      )
      .optional(),
  })
  .describe(
    'Per-tenant merchant accounts. A provider a tenant omits is simply unavailable for that tenant.',
  );

const mailSchema = z
  .strictObject({
    host: z.string().min(1),
    port: z.number(),
    secure: z.boolean().optional(),
    user: z.string().min(1),
    password: z.string().min(1),
    email: z.string().describe('From address; defaults to user.').optional(),
    maxConnections: positiveInteger()
      .describe(
        "Connections this tenant's mail account may hold open at once. A mail server limits concurrency per sender, so the ceiling belongs to the account — a Microsoft 365 mailbox allows three. Tenants sharing a mailbox share one pool and one ceiling, so they must agree on this value or the configuration is refused at startup. Defaults to 10.",
      )
      .optional(),
  })
  .describe('Per-tenant SMTP settings.');

const oauthSchema = z
  .strictObject({
    google: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
      })
      .optional(),
    keycloak: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        issuer: z
          .string()
          .min(1)
          .describe(
            'Keycloak realm issuer URL, with or without a trailing slash. Each tenant uses its own realm.',
          )
          /* A trailing slash and no trailing slash are two spellings of the same
           * issuer and both correct. Settled to one of them so the discovery
           * address built from it is well-formed either way: the doubled slash
           * the other spelling produces resolves to no discovery document, which
           * is read as a sign-in starts, so the tenant's Keycloak sign-in fails
           * before the visitor reaches the realm at all. A value that is not
           * another spelling of the same issuer but a mistake — no scheme, or an
           * issuer already ending in the discovery path — is left to fail rather
           * than repaired. */
          .transform(issuer => issuer.replace(/\/+$/, '')),
      })
      .optional(),
  })
  .describe(
    "Per-tenant OAuth applications. Each provider is registered at startup under the provider id '<provider>-<tenantId>' — register the matching redirect URI (/api/auth/oauth2/callback/<provider>-<tenantId>) with the identity provider. There is no global app: a tenant offers a provider only when it declares it here.",
  );

export const tenantConfigSchema = z.strictObject({
  db: z.strictObject({
    url: z
      .string()
      .min(1)
      .describe(
        "Postgres connection URL of this tenant's own database. Every tenant has its own database; isolation is per-database.",
      ),
  }),
  aos: aosSchema,
  payments: paymentsSchema.optional(),
  mail: mailSchema.optional(),
  mattermost: z
    .strictObject({
      token: z.string().describe('Mattermost admin token.').optional(),
      createUsers: z
        .boolean()
        .describe('Create Mattermost users on registration.')
        .optional(),
    })
    .describe(
      'The Mattermost host is browser-facing — set it per tenant via publicEnv.GOOVEE_PUBLIC_MATTERMOST_HOST.',
    )
    .optional(),
  oauth: oauthSchema.optional(),
  webPush: z
    .strictObject({
      privateKey: z.string().min(1),
      subject: z
        .string()
        .min(1)
        .describe(
          'mailto: address or https: URL identifying the sender to push services.',
        ),
    })
    .describe(
      'Web-push signing identity; the public key lives in publicEnv.GOOVEE_PUBLIC_VAPID_PUBLIC_KEY. The service worker registers per tenant (scope /<tenant>/), so each tenant holds its own push subscription and its own key pair takes effect even on a shared origin.',
    )
    .optional(),
  includeLanguage: z
    .boolean()
    .describe(
      "Also load the base language (e.g. 'en' for 'en-US') in addition to the specific locale. Defaults to false.",
    )
    .optional(),
  uploadRecordRetentionHours: z
    .number()
    .describe(
      'How long terminal staged-upload records are kept before the prune sweep deletes them. Defaults to 168 (7 days).',
    )
    .optional(),
  publicEnv: publicEnvSchema,
});

export type TenantConfig = z.output<typeof tenantConfigSchema>;
export type GlobalConfig = z.output<typeof globalConfigSchema>;

/* The two sections as a document holds them, before the parse settles the
 * storage root and the Keycloak issuer. What writes a document rather than reads
 * one — the environment migration — builds these shapes, which match the parsed
 * ones only for as long as no setting is given a default or a coercion. */
export type TenantConfigInput = z.input<typeof tenantConfigSchema>;
export type GlobalConfigInput = z.input<typeof globalConfigSchema>;

type TenantEntry = [string, TenantConfig];

/* A violated document-wide invariant, reported against the field that has to
 * change rather than against the document. */
type ConfigIssue = {path: string[]; message: string};

/* Cross-tenant invariant. A HUB PISP tenant authenticates to BPCE with an mTLS
 * client certificate loaded from its certsDir (client.crt + private-key.pem) —
 * that certificate IS the tenant's enrolled bank identity, so two tenants must
 * never resolve to the same certsDir or they would transact as the same bank
 * client. certsDir is required per tenant, so this only has to reject two
 * tenants that point at the same directory. Paths are resolved to absolute so
 * equivalent specs (relative vs absolute, trailing slash) compare equal. */
function checkHubPispCertIsolation(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const byCertsDir = new Map<string, string>(); // resolved certsDir -> tenant id

  for (const [id, config] of tenants) {
    const configured = config.payments?.hubpisp?.certsDir;
    if (!configured) continue;

    const certsDir = path.resolve(configured);
    const owner = byCertsDir.get(certsDir);

    if (owner) {
      issues.push({
        path: [id, 'payments', 'hubpisp', 'certsDir'],
        message:
          `Tenants "${owner}" and "${id}" share the same HUB PISP certsDir ` +
          `("${certsDir}"). Each HUB PISP tenant needs its own mTLS client ` +
          `certificate — set a distinct payments.hubpisp.certsDir per tenant.`,
      });
      continue;
    }

    byCertsDir.set(certsDir, id);
  }

  return issues;
}

/* Cross-tenant invariant. Uploads are recorded as a path relative to the tenant's
 * storage root, so two tenants resolving to the same root share one namespace:
 * each would resolve the other's recorded paths, and the retention sweep would
 * delete from a directory holding another tenant's blobs. The roots compared here
 * are the resolved ones — a tenant on a shared AOS already has its aosTenantId
 * subdirectory baked in — so tenants sharing one AOS legitimately pass. */
function checkStorageIsolation(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const roots: Array<[string, string]> = []; // [tenant id, resolved storage root]

  for (const [id, config] of tenants) {
    const storage = path.resolve(config.aos.storage);

    for (const [owner, existing] of roots) {
      /* Containment, not just equality: a tenant that keeps the base path (no
       * aosTenantId) while another sits in a subdirectory of it would otherwise
       * pass, and the outer tenant's root then contains the inner one's — its
       * recorded paths resolve into the inner tenant's files and its retention
       * sweep deletes from them. */
      const nested =
        storage === existing ||
        storage.startsWith(existing + path.sep) ||
        existing.startsWith(storage + path.sep);

      if (nested) {
        issues.push({
          path: [id, 'aos', 'storage'],
          message:
            `Tenants "${owner}" ("${existing}") and "${id}" ("${storage}") share ` +
            `a storage root — one contains the other. Give each tenant a ` +
            `directory of its own, or set aos.aosTenantId on every tenant that ` +
            `shares one AOS instance.`,
        });
      }
    }

    roots.push([id, storage]);
  }

  return issues;
}

/* Cross-tenant invariant. Tenants sharing one mail account share one connection
 * pool, so they must agree on how many connections that account allows: the pool
 * is built by whichever tenant sends first, and a disagreement would make the
 * ceiling depend on send order — intermittently exceeding the limit the lower
 * value was set to respect. */
function checkMailCeilings(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const byAccount = new Map<string, {id: string; maxConnections: number}>();

  for (const [id, config] of tenants) {
    const mail = config.mail;
    if (!mail?.host) continue;

    const account = mailAccountKey(mail);
    const existing = byAccount.get(account);

    /* Compared as they are applied, not as they are written: leaving the setting
     * out means the default, so a tenant that omits it agrees with one that
     * spells that same number out. Refusing those would make an operator edit a
     * file to state what the two configurations already mean. */
    const maxConnections = getMaxConnections(mail);

    if (existing && existing.maxConnections !== maxConnections) {
      issues.push({
        path: [id, 'mail', 'maxConnections'],
        message:
          `Tenants "${existing.id}" and "${id}" share the mail account ` +
          `"${mail.user}" on ${mail.host} but allow it a different number of ` +
          `connections (${existing.maxConnections} and ${maxConnections}). ` +
          `They share one connection pool, so the ceiling must match — set ` +
          `mail.maxConnections to the same value for both.`,
      });
      continue;
    }

    if (!existing) {
      byAccount.set(account, {id, maxConnections});
    }
  }

  return issues;
}

/* Checked against the tenants, because the two halves of the document are
 * edited separately. Rename or drop a tenant and this can be left pointing at
 * an entry that is not there, and the addresses it serves answer not-found with
 * no explanation. */
function checkDefaultTenant(
  defaultTenant: string | undefined,
  ids: string[],
): ConfigIssue[] {
  if (!defaultTenant || ids.includes(defaultTenant)) {
    return [];
  }

  return [
    {
      path: ['$global', 'defaultTenant'],
      message:
        `"${defaultTenant}" names no tenant in this document, which names ` +
        `${ids.join(', ')}.`,
    },
  ];
}

/* Cross-tenant invariant. The auth cookie names are settled once, as the auth
 * instance is built, from the scheme $global.betterAuthUrl carries, so one naming
 * serves every origin in the document and the schemes have to agree. Where they
 * do not: an http tenant under an https deployment is sent `__Secure-` cookies a
 * browser refuses over http and holds no session at all, and an https tenant
 * under an http deployment is sent cookies carrying neither the prefix nor the
 * Secure attribute. Both are refused. */
function checkOriginSchemes(
  betterAuthUrl: unknown,
  tenants: TenantEntry[],
): ConfigIssue[] {
  const deployment = parseOrigin(betterAuthUrl);

  /* Nothing to compare against, and the field's own check has already reported
   * why. Every origin below is skipped the same way, so a document with one
   * malformed origin reports that alone rather than adding a mismatch against a
   * scheme it could not read. */
  if (!deployment) return [];

  return tenants.flatMap(([id, config]) => {
    const declared = config.publicEnv.GOOVEE_PUBLIC_HOST;
    const origin = parseOrigin(declared);

    if (!origin || origin.protocol === deployment.protocol) return [];

    return [
      {
        path: [id, 'publicEnv', 'GOOVEE_PUBLIC_HOST'],
        message:
          `Tenant "${id}" is served on ${declared} while the deployment is ` +
          `served on ${deployment.origin}. Both have to use the same scheme — ` +
          `serve every origin over ${deployment.protocol.replace(':', '')}, or ` +
          `change $global.betterAuthUrl to match.`,
      },
    ];
  });
}

function checkTenantIds(ids: string[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];

  for (const id of ids) {
    if (!TENANT_ID_PATTERN.test(id)) {
      issues.push({
        path: [id],
        message:
          `"${id}" is not a usable tenant id. A tenant id is the URL path ` +
          `segment it is served under: a letter, then letters, digits or ` +
          `hyphens.`,
      });
      continue;
    }

    if (isReservedSegment(id)) {
      issues.push({
        path: [id],
        message:
          `"${id}" cannot be a tenant id: the deployment answers /${id} ` +
          `itself, so no request would reach a tenant named this. Reserved: ` +
          `${reservedSegments().join(', ')}.`,
      });
      continue;
    }

    if (id.length > TENANT_ID_MAX_LENGTH) {
      issues.push({
        path: [id],
        message:
          `"${id}" is ${id.length} characters, and a tenant id may hold at ` +
          `most ${TENANT_ID_MAX_LENGTH}. A Hub PISP payment carries its ` +
          `reference as "<paymentContextId>-<tenantId>" in a field of 35 ` +
          `characters, and a context id can reach 19 digits, so a longer id ` +
          `works until this tenant's context ids grow and then fails every Hub ` +
          `PISP payment it attempts.`,
      });
    }
  }

  return issues;
}

function tenantEntries(document: Record<string, unknown>): TenantEntry[] {
  return Object.entries(document)
    .filter(([key]) => !RESERVED_DOCUMENT_KEYS.includes(key))
    .map(([id, config]): TenantEntry => [id, config as TenantConfig]);
}

/*
 * The whole document: the reserved "$global" section plus one entry per tenant,
 * keyed by tenant id.
 *
 * The per-tenant entries are the catchall rather than a named property, which is
 * what lets an operator name their own tenants. `propertyNames` is carried in
 * the metadata because the generated schema can express the id restriction while
 * a catchall cannot; the load enforces it below, where the message can say what
 * an id is for.
 */
export const configDocumentSchema = z
  .object({
    $schema: z.string().optional(),
    $global: globalConfigSchema,
  })
  .catchall(tenantConfigSchema)
  .meta({
    title: 'Goovee configuration',
    description:
      'The single configuration document for Goovee — a reserved "$global" section (deployment-wide settings) plus one entry per tenant, keyed by the tenant id (the URL path segment: a letter, then letters, digits or hyphens, at most 15 characters, because a Hub PISP payment reference carries the id after a payment context id of up to 19 digits in a field of 35). Set TENANTS_CONFIG_FILE or TENANTS_CONFIG to point at it. Single-tenant is a one-entry document under any id, and that id is the segment every address of the deployment carries. Nothing is inherited: a section a tenant omits is simply off for that tenant, never filled from the environment or another tenant.',
    propertyNames: {
      pattern: `^(\\$schema|\\$global|[a-zA-Z][a-zA-Z0-9-]{0,${TENANT_ID_MAX_LENGTH - 1}})$`,
    },
  })
  /* These see a document that parsed — a field of the wrong type, a missing one,
   * or a setting name no section declares stops the parse before this — but not
   * one every field accepted. A failed refinement leaves its value in place and
   * the document still arrives here, so a check can read a field a refinement has
   * just rejected; and a transform behind a failed refinement has not run, so a
   * value can arrive neither as written nor as the application would use it.
   *
   * A check reading such a value has to skip it: reporting against it repeats a
   * fault the field already reported, or invents one, and a throw raised here
   * escapes the parse to be reported against neither a field nor a tenant. */
  .check(ctx => {
    const tenants = tenantEntries(ctx.value);

    const ids = tenants.map(([id]) => id);

    const issues = [
      ...checkTenantIds(ids),
      ...(tenants.length
        ? [
            ...checkDefaultTenant(ctx.value.$global?.defaultTenant, ids),
            ...checkOriginSchemes(ctx.value.$global?.betterAuthUrl, tenants),
            ...checkHubPispCertIsolation(tenants),
            ...checkStorageIsolation(tenants),
            ...checkMailCeilings(tenants),
          ]
        : [{path: [], message: 'Tenant configuration has no tenant entries'}]),
    ];

    for (const issue of issues) {
      ctx.issues.push({
        code: 'custom',
        input: ctx.value,
        path: issue.path,
        message: issue.message,
      });
    }
  });
