/*
 * The configuration document's shape, in one place.
 *
 * Three things are derived from what is written here: the parse every document
 * is admitted by, the TypeScript types the application reads configuration
 * through, and tenants.config.schema.json — generated by `pnpm config:schema`,
 * and what an operator's editor validates the document against. Adding a
 * setting means adding it here and regenerating, rather than writing it into a
 * type, a check and a schema file that are free to disagree.
 *
 * A `describe()` string is operator-facing: it is what the generated schema
 * carries and what an editor shows while the document is being written.
 */

import path from 'path';

import {z} from 'zod';

import {
  getMaxConnections,
  mailAccountKey,
} from '@/lib/core/notification/mail-account';

/* $schema is an editor hint and $global holds the deployment-wide settings.
 * Every other key in the document names a tenant. */
const RESERVED_DOCUMENT_KEYS = ['$schema', '$global'];

/* A tenant id is the URL path segment the tenant is served under, and the proxy
 * reads that segment with a letters-only pattern of its own (`extractTenant` in
 * proxy.ts), so an id holding anything else names an entry that no request can
 * reach. Widening this obliges widening that pattern too. */
const TENANT_ID_PATTERN = /^[a-zA-Z]+$/;

/*
 * A positive whole number.
 *
 * Rejected at load rather than corrected at the point of use: a setting
 * silently replaced by a default is how a deployment ends up believing it set
 * three and running at ten.
 */
const positiveInteger = () => z.int().min(1);

export const globalConfigSchema = z
  .strictObject({
    betterAuthSecret: z
      .string()
      .min(1)
      .describe(
        'Better Auth signing/encryption secret (the BETTER_AUTH_SECRET equivalent).',
      ),
    betterAuthUrl: z
      .string()
      .min(1)
      /* Checked here because this is the one malformed spelling that fails in
       * silence: a base URL already carrying a path makes the auth library drop
       * the configured base path, mount its routes on that path instead, and
       * answer every auth request with a 404 — no startup error, nothing
       * logged. A value with no scheme, or one that is not a URL at all, throws
       * as the auth instance is built and names itself. */
      .refine(
        value => {
          try {
            const url = new URL(value);
            return (
              (url.protocol === 'http:' || url.protocol === 'https:') &&
              url.pathname === '/' &&
              url.search === '' &&
              url.hash === ''
            );
          } catch {
            return false;
          }
        },
        {
          error:
            'must be an origin — scheme and host with no path, e.g. ' +
            'https://portal.example.com',
        },
      )
      .meta({
        description:
          "Origin the deployment is served on, e.g. https://portal.example.com — scheme and host only, with no path: the base path is appended in code, and a path here answers every auth request with a 404. Required: left out, Better Auth resolves it from the environment instead, where an unrelated BASE_URL becomes this deployment's auth origin and its only trusted origin.",
        pattern: '^https?://[^/?#]+/?$',
      }),
    pushMaxConnections: positiveInteger()
      .describe(
        'Push deliveries in flight at once, and sockets held per push service. One agent serves the whole process, so this bounds the deployment. Defaults to 10.',
      )
      .optional(),
    imageCacheMaxBytes: positiveInteger()
      .describe(
        "Bytes the resized-image cache may occupy. One cache directory serves every tenant, so the budget is the deployment's.",
      )
      .optional(),
  })
  .describe(
    'Deployment-wide settings, shared by every tenant because they are bound to the single origin / process.',
  );

const publicEnvSchema = z
  .strictObject({
    GOOVEE_PUBLIC_HOST: z
      .string()
      .min(1)
      .describe(
        'Required. Workspace URLs are stored against this host and every absolute link is built from it, so a tenant without one resolves no workspace.',
      ),
    GOOVEE_PUBLIC_PAYPAL_CLIENT_ID: z.string().optional(),
    GOOVEE_PUBLIC_LINKEDIN_URL: z.string().optional(),
    GOOVEE_PUBLIC_TWITTER_URL: z.string().optional(),
    GOOVEE_PUBLIC_INSTAGRAM_URL: z.string().optional(),
    GOOVEE_PUBLIC_WHATSAPP_URL: z.string().optional(),
    GOOVEE_PUBLIC_MATTERMOST_HOST: z.string().optional(),
    GOOVEE_PUBLIC_VAPID_PUBLIC_KEY: z.string().optional(),
    GOOVEE_PUBLIC_KEYCLOAK_OAUTH_BUTTON_LABEL: z.string().optional(),
    GOOVEE_PUBLIC_KEYCLOAK_OAUTH_BUTTON_IMAGE: z.string().optional(),
  })
  .describe(
    'Browser-exposed variables for this tenant (declared in full; not inherited from the environment).',
  );

/* The browser-exposed variables the app supports, taken from the schema so that
 * what a tenant may declare and what the app delivers cannot drift apart. */
export type PublicEnvKey = keyof z.output<typeof publicEnvSchema>;

/* The cast holds because a shape's keys are the keys of the type inferred from
 * it. */
export const PUBLIC_ENV_KEYS = Object.keys(
  publicEnvSchema.shape,
) as PublicEnvKey[];

const aosAuthSchema = z
  .strictObject({
    apiKey: z.string().optional(),
    username: z.string().optional(),
    password: z.string().optional(),
  })
  .refine(auth => !!auth.apiKey || !!(auth.username && auth.password), {
    error: 'requires apiKey, or username and password',
  })
  /* The alternative is a refinement, which no JSON Schema keyword expresses, so
   * the generated schema would accept credentials the load then refuses. Stated
   * here as well, in the keyword an editor understands. */
  .meta({
    description:
      'AOS credentials: apiKey (AOS 9+, generated in AOS under Preferences → API Keys) or username/password basic auth. apiKey wins when both are set.',
    anyOf: [{required: ['apiKey']}, {required: ['username', 'password']}],
  });

const aosSchema = z
  .strictObject({
    url: z
      .string()
      .min(1)
      .describe(
        'Base URL of the AOS instance, e.g. https://erp.example.com/axelor-erp. Unique per tenant in topology A (dedicated AOS); shared across tenants in topology B (AOS multi-tenancy).',
      ),
    aosTenantId: z
      .string()
      .describe(
        'AOS-side tenant id — independent of the Goovee tenant id. Set it when this tenant lives on a shared AOS instance with AOS multi-tenancy (topology B): every AOS call then carries X-Tenant-ID with this value. Leave unset for a dedicated AOS instance (topology A).',
      )
      .optional(),
    storage: z
      .string()
      .min(1)
      .describe(
        "The AOS instance's data.upload.dir base path (created on first connect; back it with a mounted volume so uploads survive). When aosTenantId is set (topology B), goovee reads and writes files under <storage>/<aosTenantId> to match AOP's per-tenant subdirectory; a dedicated instance (topology A) uses this path as-is.",
      ),
    auth: aosAuthSchema,
    webhookSecret: z
      .string()
      .describe(
        'Secret AOS uses to sign notification webhooks for this tenant (the NOTIFICATION_WEBHOOK_SECRET equivalent).',
      )
      .optional(),
  })
  /* Bake the per-tenant storage root once, mirroring AOP's
   * FileSystemStore.getRootPath(): a tenant on a shared multi-tenant AOS keeps
   * its files under <data.upload.dir>/<aosTenantId>, while a dedicated instance
   * (or the AOP "default" tenant) uses <data.upload.dir> as-is. goovee reads and
   * writes the AOS filesystem directly, so every storage consumer can use
   * config.aos.storage verbatim without re-deriving the subdirectory. */
  .transform(aos => ({
    ...aos,
    storage:
      aos.aosTenantId && aos.aosTenantId !== 'default'
        ? path.join(aos.storage, aos.aosTenantId)
        : aos.storage,
  }));

const paymentsSchema = z
  .strictObject({
    paypal: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        live: z
          .boolean()
          .describe('true for live payments; defaults to sandbox.')
          .optional(),
      })
      .optional(),
    stripe: z
      .strictObject({
        clientSecret: z.string().min(1),
        webhookSecret: z
          .string()
          .describe(
            "Stripe webhook signing secret for this tenant's webhook endpoint.",
          )
          .optional(),
      })
      .optional(),
    paybox: z
      .strictObject({
        site: z.string().min(1),
        rang: z.string().min(1),
        identifiant: z.string().min(1),
        secret: z.string().min(1),
        paybox: z.string().min(1).describe('Paybox payment page base URL.'),
        backup1: z.string().optional(),
        backup2: z.string().optional(),
      })
      .optional(),
    up2pay: z
      .strictObject({
        site: z.string().min(1),
        rang: z.string().min(1),
        identifiant: z.string().min(1),
        secret: z.string().min(1),
        paybox: z.string().min(1).describe('Up2Pay payment page base URL.'),
        legacyForwardUrl: z
          .string()
          .describe(
            'Where to forward Up2Pay IPNs this tenant cannot attribute to a Goovee payment (legacy-ERP invoices, unknown context). Omit to not forward.',
          )
          .optional(),
      })
      .optional(),
    hubpisp: z
      .strictObject({
        tokenUrl: z.string().min(1),
        apiUrl: z.string().min(1),
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        certFingerprint: z.string().min(1),
        beneficiaryName: z.string().min(1),
        iban: z.string().min(1),
        bic: z.string().optional(),
        certsDir: z
          .string()
          .min(1)
          .describe(
            "Required. Directory holding this tenant's mTLS client.crt and private-key.pem. Must be distinct per HUB PISP tenant — the certificate is the tenant's bank identity, so there is no shared default. Uniqueness is enforced at config load, not by this schema.",
          ),
      })
      .describe(
        "Register this tenant's BPCE webhook under the tenant-scoped path /api/tenant/<tenantId>/webhooks/hubpisp/... so the webhook uses this tenant's credentials.",
      )
      .optional(),
  })
  .describe(
    'Per-tenant merchant accounts. A provider a tenant omits is simply unavailable for that tenant.',
  );

const mailSchema = z
  .strictObject({
    host: z.string().min(1),
    port: z.number(),
    secure: z.boolean().optional(),
    user: z.string().min(1),
    password: z.string().min(1),
    email: z.string().describe('From address; defaults to user.').optional(),
    maxConnections: positiveInteger()
      .describe(
        "Connections this tenant's mail account may hold open at once. A mail server limits concurrency per sender, so the ceiling belongs to the account — a Microsoft 365 mailbox allows three. Tenants sharing a mailbox share one pool and one ceiling, so they must agree on this value or the configuration is refused at startup. Defaults to 10.",
      )
      .optional(),
  })
  .describe('Per-tenant SMTP settings.');

const oauthSchema = z
  .strictObject({
    google: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
      })
      .optional(),
    keycloak: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        issuer: z
          .string()
          .min(1)
          .describe(
            'Keycloak realm issuer URL, with or without a trailing slash. Each tenant uses its own realm.',
          )
          /* A trailing slash and no trailing slash are two spellings of the same
           * issuer and both correct. Settled to one of them so the discovery
           * address built from it is well-formed either way: the doubled slash
           * the other spelling produces resolves to no discovery document, which
           * is read as a sign-in starts, so the tenant's Keycloak sign-in fails
           * before the visitor reaches the realm at all. A value that is not
           * another spelling of the same issuer but a mistake — no scheme, or an
           * issuer already ending in the discovery path — is left to fail rather
           * than repaired. */
          .transform(issuer => issuer.replace(/\/+$/, '')),
      })
      .optional(),
  })
  .describe(
    "Per-tenant OAuth applications. Each provider is registered at startup under the provider id '<provider>-<tenantId>' — register the matching redirect URI (/api/auth/oauth2/callback/<provider>-<tenantId>) with the identity provider. There is no global app: a tenant offers a provider only when it declares it here.",
  );

export const tenantConfigSchema = z.strictObject({
  db: z.strictObject({
    url: z
      .string()
      .min(1)
      .describe(
        "Postgres connection URL of this tenant's own database. Every tenant has its own database; isolation is per-database.",
      ),
  }),
  aos: aosSchema,
  payments: paymentsSchema.optional(),
  mail: mailSchema.optional(),
  mattermost: z
    .strictObject({
      token: z.string().describe('Mattermost admin token.').optional(),
      createUsers: z
        .boolean()
        .describe('Create Mattermost users on registration.')
        .optional(),
    })
    .describe(
      'The Mattermost host is browser-facing — set it per tenant via publicEnv.GOOVEE_PUBLIC_MATTERMOST_HOST.',
    )
    .optional(),
  oauth: oauthSchema.optional(),
  webPush: z
    .strictObject({
      privateKey: z.string().min(1),
      subject: z
        .string()
        .min(1)
        .describe(
          'mailto: address or https: URL identifying the sender to push services.',
        ),
    })
    .describe(
      'Web-push signing identity; the public key lives in publicEnv.GOOVEE_PUBLIC_VAPID_PUBLIC_KEY. The service worker registers per tenant (scope /<tenant>/), so each tenant holds its own push subscription and its own key pair takes effect even on a shared origin.',
    )
    .optional(),
  includeLanguage: z
    .boolean()
    .describe(
      "Also load the base language (e.g. 'en' for 'en-US') in addition to the specific locale. Defaults to false.",
    )
    .optional(),
  uploadRecordRetentionHours: z
    .number()
    .describe(
      'How long terminal staged-upload records are kept before the prune sweep deletes them. Defaults to 168 (7 days).',
    )
    .optional(),
  publicEnv: publicEnvSchema,
});

export type TenantConfig = z.output<typeof tenantConfigSchema>;
export type GlobalConfig = z.output<typeof globalConfigSchema>;

/* The two sections as a document holds them, before the parse settles the
 * storage root and the Keycloak issuer. What writes a document rather than reads
 * one — the environment migration — builds these shapes, which match the parsed
 * ones only for as long as no setting is given a default or a coercion. */
export type TenantConfigInput = z.input<typeof tenantConfigSchema>;
export type GlobalConfigInput = z.input<typeof globalConfigSchema>;

type TenantEntry = [string, TenantConfig];

/* A violated document-wide invariant, reported against the field that has to
 * change rather than against the document. */
type ConfigIssue = {path: string[]; message: string};

/* Cross-tenant invariant. A HUB PISP tenant authenticates to BPCE with an mTLS
 * client certificate loaded from its certsDir (client.crt + private-key.pem) —
 * that certificate IS the tenant's enrolled bank identity, so two tenants must
 * never resolve to the same certsDir or they would transact as the same bank
 * client. certsDir is required per tenant, so this only has to reject two
 * tenants that point at the same directory. Paths are resolved to absolute so
 * equivalent specs (relative vs absolute, trailing slash) compare equal. */
function checkHubPispCertIsolation(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const byCertsDir = new Map<string, string>(); // resolved certsDir -> tenant id

  for (const [id, config] of tenants) {
    const configured = config.payments?.hubpisp?.certsDir;
    if (!configured) continue;

    const certsDir = path.resolve(configured);
    const owner = byCertsDir.get(certsDir);

    if (owner) {
      issues.push({
        path: [id, 'payments', 'hubpisp', 'certsDir'],
        message:
          `Tenants "${owner}" and "${id}" share the same HUB PISP certsDir ` +
          `("${certsDir}"). Each HUB PISP tenant needs its own mTLS client ` +
          `certificate — set a distinct payments.hubpisp.certsDir per tenant.`,
      });
      continue;
    }

    byCertsDir.set(certsDir, id);
  }

  return issues;
}

/* Cross-tenant invariant. Uploads are recorded as a path relative to the tenant's
 * storage root, so two tenants resolving to the same root share one namespace:
 * each would resolve the other's recorded paths, and the retention sweep would
 * delete from a directory holding another tenant's blobs. The roots compared here
 * are the resolved ones — a tenant on a shared AOS already has its aosTenantId
 * subdirectory baked in — so tenants sharing one AOS legitimately pass. */
function checkStorageIsolation(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const roots: Array<[string, string]> = []; // [tenant id, resolved storage root]

  for (const [id, config] of tenants) {
    const storage = path.resolve(config.aos.storage);

    for (const [owner, existing] of roots) {
      /* Containment, not just equality: a tenant that keeps the base path (no
       * aosTenantId) while another sits in a subdirectory of it would otherwise
       * pass, and the outer tenant's root then contains the inner one's — its
       * recorded paths resolve into the inner tenant's files and its retention
       * sweep deletes from them. */
      const nested =
        storage === existing ||
        storage.startsWith(existing + path.sep) ||
        existing.startsWith(storage + path.sep);

      if (nested) {
        issues.push({
          path: [id, 'aos', 'storage'],
          message:
            `Tenants "${owner}" ("${existing}") and "${id}" ("${storage}") share ` +
            `a storage root — one contains the other. Give each tenant a ` +
            `directory of its own, or set aos.aosTenantId on every tenant that ` +
            `shares one AOS instance.`,
        });
      }
    }

    roots.push([id, storage]);
  }

  return issues;
}

/* Cross-tenant invariant. Tenants sharing one mail account share one connection
 * pool, so they must agree on how many connections that account allows: the pool
 * is built by whichever tenant sends first, and a disagreement would make the
 * ceiling depend on send order — intermittently exceeding the limit the lower
 * value was set to respect. */
function checkMailCeilings(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const byAccount = new Map<string, {id: string; maxConnections: number}>();

  for (const [id, config] of tenants) {
    const mail = config.mail;
    if (!mail?.host) continue;

    const account = mailAccountKey(mail);
    const existing = byAccount.get(account);

    /* Compared as they are applied, not as they are written: leaving the setting
     * out means the default, so a tenant that omits it agrees with one that
     * spells that same number out. Refusing those would make an operator edit a
     * file to state what the two configurations already mean. */
    const maxConnections = getMaxConnections(mail);

    if (existing && existing.maxConnections !== maxConnections) {
      issues.push({
        path: [id, 'mail', 'maxConnections'],
        message:
          `Tenants "${existing.id}" and "${id}" share the mail account ` +
          `"${mail.user}" on ${mail.host} but allow it a different number of ` +
          `connections (${existing.maxConnections} and ${maxConnections}). ` +
          `They share one connection pool, so the ceiling must match — set ` +
          `mail.maxConnections to the same value for both.`,
      });
      continue;
    }

    if (!existing) {
      byAccount.set(account, {id, maxConnections});
    }
  }

  return issues;
}

function checkTenantIds(ids: string[]): ConfigIssue[] {
  return ids
    .filter(id => !TENANT_ID_PATTERN.test(id))
    .map(id => ({
      path: [id],
      message:
        `"${id}" is not a usable tenant id. A tenant id is the URL path ` +
        `segment it is served under, so it may hold letters only.`,
    }));
}

function tenantEntries(document: Record<string, unknown>): TenantEntry[] {
  return Object.entries(document)
    .filter(([key]) => !RESERVED_DOCUMENT_KEYS.includes(key))
    .map(([id, config]): TenantEntry => [id, config as TenantConfig]);
}

/*
 * The whole document: the reserved "$global" section plus one entry per tenant,
 * keyed by tenant id.
 *
 * The per-tenant entries are the catchall rather than a named property, which is
 * what lets an operator name their own tenants. `propertyNames` is carried in
 * the metadata because the generated schema can express the id restriction while
 * a catchall cannot; the load enforces it below, where the message can say what
 * an id is for.
 */
export const configDocumentSchema = z
  .object({
    $schema: z.string().optional(),
    $global: globalConfigSchema,
  })
  .catchall(tenantConfigSchema)
  .meta({
    title: 'Goovee configuration',
    description:
      'The single configuration document for Goovee — a reserved "$global" section (deployment-wide settings) plus one entry per tenant, keyed by the tenant id (the URL path segment, letters only). Set TENANTS_CONFIG_FILE or TENANTS_CONFIG to point at it. Single-tenant is just a one-entry document keyed "d". Nothing is inherited: a section a tenant omits is simply off for that tenant, never filled from the environment or another tenant.',
    propertyNames: {pattern: '^(\\$schema|\\$global|[a-zA-Z]+)$'},
  })
  /* Only reached once every entry is individually valid, so these see a whole
   * document and nothing half-parsed. */
  .check(ctx => {
    const tenants = tenantEntries(ctx.value);

    const issues = [
      ...checkTenantIds(tenants.map(([id]) => id)),
      ...(tenants.length
        ? [
            ...checkHubPispCertIsolation(tenants),
            ...checkStorageIsolation(tenants),
            ...checkMailCeilings(tenants),
          ]
        : [{path: [], message: 'Tenant configuration has no tenant entries'}]),
    ];

    for (const issue of issues) {
      ctx.issues.push({
        code: 'custom',
        input: ctx.value,
        path: issue.path,
        message: issue.message,
      });
    }
  });
